server:
  port: 9110
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-d.credentials.uri:http://localhost:8788/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
---
#Zull Routing Configuration
zuul:
  prefix: /api
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    ms-client-1 : /client1/
    
#Turbine Configuration
turbine:
  appConfig: ms-gateway
  aggregator:
     clusterConfig: MS-GATEWAY

#Disable Default FallBack for FeignCLient while invoking Other Micro Service
feign:
 hystrix:
   enabled: false
   
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
#app:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
#Disable Default Exception for Feign Client while invoking Authentication Micro Service
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false
            
---
logging:
  config: classpath:logback-local.xml
  
---
swagger: 
  flag: true
  
#COnfiguration for static images 
ms: 
 media: 
   baseURL: file:/C:/ms/test/watch/
   mappingURL: /watch/**
   