server:
  port: 9100
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8788/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
#Disable Default FallBack for FeignCLient while invoking Other Micro Service
feign:
 hystrix:
   enabled: false
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
#app:
#  ConnectTimeout: 5000
#  ReadTimeout: 5000
#Disable Default Exception for Feign Client while invoking Other Micro Service
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false
            
---
#Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms-test?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect : org.hibernate.dialect.MySQLDialect
        #hbm2ddl:
          #auto: create
  data:
    mongodb:
      database: ms-test
      host: localhost
      port: 27017
      
---
spring:
  profiles: prd
eureka:
  instance:
    nonSecurePort: 80

---    
logging:
  config: classpath:logback-prd.xml
  
---
swagger:
  flag: false
  